# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ChangeNames.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(900, 900)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("ExternalFiles/Python_Icon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_FP = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_FP.setFont(font)
        self.label_FP.setObjectName(_fromUtf8("label_FP"))
        self.verticalLayout.addWidget(self.label_FP)
        self.label_Old = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Old.setFont(font)
        self.label_Old.setObjectName(_fromUtf8("label_Old"))
        self.verticalLayout.addWidget(self.label_Old)
        self.label_New = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_New.setFont(font)
        self.label_New.setObjectName(_fromUtf8("label_New"))
        self.verticalLayout.addWidget(self.label_New)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.textEdit_FP = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_FP.sizePolicy().hasHeightForWidth())
        self.textEdit_FP.setSizePolicy(sizePolicy)
        self.textEdit_FP.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        self.textEdit_FP.setFont(font)
        self.textEdit_FP.setTabChangesFocus(True)
        self.textEdit_FP.setObjectName(_fromUtf8("textEdit_FP"))
        self.verticalLayout_3.addWidget(self.textEdit_FP)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.textEdit_Old = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_Old.sizePolicy().hasHeightForWidth())
        self.textEdit_Old.setSizePolicy(sizePolicy)
        self.textEdit_Old.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        self.textEdit_Old.setFont(font)
        self.textEdit_Old.setTabChangesFocus(True)
        self.textEdit_Old.setObjectName(_fromUtf8("textEdit_Old"))
        self.gridLayout_2.addWidget(self.textEdit_Old, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(330, 28, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(330, 28, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        self.textEdit_New = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_New.sizePolicy().hasHeightForWidth())
        self.textEdit_New.setSizePolicy(sizePolicy)
        self.textEdit_New.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        self.textEdit_New.setFont(font)
        self.textEdit_New.setTabChangesFocus(True)
        self.textEdit_New.setObjectName(_fromUtf8("textEdit_New"))
        self.gridLayout_2.addWidget(self.textEdit_New, 1, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.pushButton_FP = QtGui.QPushButton(self.centralwidget)
        self.pushButton_FP.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_FP.setFont(font)
        self.pushButton_FP.setAutoDefault(True)
        self.pushButton_FP.setObjectName(_fromUtf8("pushButton_FP"))
        self.verticalLayout_4.addWidget(self.pushButton_FP)
        spacerItem2 = QtGui.QSpacerItem(20, 75, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem3 = QtGui.QSpacerItem(253, 25, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.horizontalLayout.addItem(spacerItem3)
        spacerItem4 = QtGui.QSpacerItem(20, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.textBrowser_Terminal = QtGui.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        self.textBrowser_Terminal.setFont(font)
        self.textBrowser_Terminal.setTabChangesFocus(True)
        self.textBrowser_Terminal.setObjectName(_fromUtf8("textBrowser_Terminal"))
        self.verticalLayout_2.addWidget(self.textBrowser_Terminal)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.checkBox_Preview = QtGui.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_Preview.setFont(font)
        self.checkBox_Preview.setChecked(True)
        self.checkBox_Preview.setTristate(False)
        self.checkBox_Preview.setObjectName(_fromUtf8("checkBox_Preview"))
        self.horizontalLayout_2.addWidget(self.checkBox_Preview)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.pushButton_Clear = QtGui.QPushButton(self.centralwidget)
        self.pushButton_Clear.setMinimumSize(QtCore.QSize(50, 30))
        self.pushButton_Clear.setMaximumSize(QtCore.QSize(100, 33))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Clear.setFont(font)
        self.pushButton_Clear.setAutoDefault(True)
        self.pushButton_Clear.setObjectName(_fromUtf8("pushButton_Clear"))
        self.horizontalLayout_2.addWidget(self.pushButton_Clear)
        self.pushButton_Run = QtGui.QPushButton(self.centralwidget)
        self.pushButton_Run.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton_Run.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_Run.setFont(font)
        self.pushButton_Run.setAutoDefault(True)
        self.pushButton_Run.setObjectName(_fromUtf8("pushButton_Run"))
        self.horizontalLayout_2.addWidget(self.pushButton_Run)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.textEdit_FP, self.pushButton_FP)
        MainWindow.setTabOrder(self.pushButton_FP, self.textEdit_Old)
        MainWindow.setTabOrder(self.textEdit_Old, self.textEdit_New)
        MainWindow.setTabOrder(self.textEdit_New, self.textBrowser_Terminal)
        MainWindow.setTabOrder(self.textBrowser_Terminal, self.checkBox_Preview)
        MainWindow.setTabOrder(self.checkBox_Preview, self.pushButton_Run)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Change Names", None))
        self.label_FP.setText(_translate("MainWindow", "Folder Path:", None))
        self.label_Old.setText(_translate("MainWindow", "Old String:", None))
        self.label_New.setText(_translate("MainWindow", "New String:", None))
        self.pushButton_FP.setText(_translate("MainWindow", "Browse", None))
        self.checkBox_Preview.setText(_translate("MainWindow", "Preview Changes Only", None))
        self.pushButton_Clear.setText(_translate("MainWindow", "Clear", None))
        self.pushButton_Run.setText(_translate("MainWindow", "Change Names", None))

